version: '3.8'
services:
  backend:
    build: .
    container_name: shortly-backend
    ports:
      - "8080:8080"
    depends_on:
      - mongo
      - redis
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongo:27017/shortlydb
      - SPRING_REDIS_HOST=redis
      - SPRING_REDIS_PORT=6379

  mongo:
    image: mongo:latest
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"

  redis:
    image: redis:latest
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
